/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export {
  discriminators,
  Addon,
  BaseResource,
  Circuit,
  CloudError,
  Cluster,
  CommonClusterProperties,
  Datastore,
  DatastoreList,
  DiskPoolVolumeProperties,
  Endpoints,
  ErrorAdditionalInfo,
  ErrorResponse,
  ExpressRouteAuthorization,
  GlobalReachConnection,
  HcxEnterpriseSite,
  IdentitySource,
  ManagementCluster,
  NetAppVolumeProperties,
  PrivateCloud,
  ProxyResource,
  Resource,
  Sku,
  TrackedResource,
  WorkloadNetworkDhcp,
  WorkloadNetworkDnsService,
  WorkloadNetworkDnsZone,
  WorkloadNetworkGateway,
  WorkloadNetworkPortMirroring,
  WorkloadNetworkSegment,
  WorkloadNetworkSegmentPortVif,
  WorkloadNetworkSegmentSubnet,
  WorkloadNetworkVirtualMachine,
  WorkloadNetworkVMGroup
} from "../models/mappers";
