/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/componentContainersMappers";
import * as Parameters from "../models/parameters";
import { AzureMachineLearningWorkspacesContext } from "../azureMachineLearningWorkspacesContext";

/** Class representing a ComponentContainers. */
export class ComponentContainers {
  private readonly client: AzureMachineLearningWorkspacesContext;

  /**
   * Create a ComponentContainers.
   * @param {AzureMachineLearningWorkspacesContext} client Reference to the service client.
   */
  constructor(client: AzureMachineLearningWorkspacesContext) {
    this.client = client;
  }

  /**
   * @summary Create or update container.
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param body Container entity to create or update.
   * @param [options] The optional parameters
   * @returns Promise<Models.ComponentContainersCreateOrUpdateResponse>
   */
  createOrUpdate(name: string, resourceGroupName: string, workspaceName: string, body: Models.ComponentContainerResource, options?: msRest.RequestOptionsBase): Promise<Models.ComponentContainersCreateOrUpdateResponse>;
  /**
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param body Container entity to create or update.
   * @param callback The callback
   */
  createOrUpdate(name: string, resourceGroupName: string, workspaceName: string, body: Models.ComponentContainerResource, callback: msRest.ServiceCallback<Models.ComponentContainerResource>): void;
  /**
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param body Container entity to create or update.
   * @param options The optional parameters
   * @param callback The callback
   */
  createOrUpdate(name: string, resourceGroupName: string, workspaceName: string, body: Models.ComponentContainerResource, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ComponentContainerResource>): void;
  createOrUpdate(name: string, resourceGroupName: string, workspaceName: string, body: Models.ComponentContainerResource, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.ComponentContainerResource>, callback?: msRest.ServiceCallback<Models.ComponentContainerResource>): Promise<Models.ComponentContainersCreateOrUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        resourceGroupName,
        workspaceName,
        body,
        options
      },
      createOrUpdateOperationSpec,
      callback) as Promise<Models.ComponentContainersCreateOrUpdateResponse>;
  }

  /**
   * @summary Get container.
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param [options] The optional parameters
   * @returns Promise<Models.ComponentContainersGetResponse>
   */
  get(name: string, resourceGroupName: string, workspaceName: string, options?: msRest.RequestOptionsBase): Promise<Models.ComponentContainersGetResponse>;
  /**
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param callback The callback
   */
  get(name: string, resourceGroupName: string, workspaceName: string, callback: msRest.ServiceCallback<Models.ComponentContainerResource>): void;
  /**
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param options The optional parameters
   * @param callback The callback
   */
  get(name: string, resourceGroupName: string, workspaceName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.ComponentContainerResource>): void;
  get(name: string, resourceGroupName: string, workspaceName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.ComponentContainerResource>, callback?: msRest.ServiceCallback<Models.ComponentContainerResource>): Promise<Models.ComponentContainersGetResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        resourceGroupName,
        workspaceName,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.ComponentContainersGetResponse>;
  }

  /**
   * @summary Delete container.
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteMethod(name: string, resourceGroupName: string, workspaceName: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param callback The callback
   */
  deleteMethod(name: string, resourceGroupName: string, workspaceName: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param name Container name.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(name: string, resourceGroupName: string, workspaceName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteMethod(name: string, resourceGroupName: string, workspaceName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        name,
        resourceGroupName,
        workspaceName,
        options
      },
      deleteMethodOperationSpec,
      callback);
  }

  /**
   * @summary List containers.
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param [options] The optional parameters
   * @returns Promise<Models.ComponentContainersListResponse>
   */
  list(resourceGroupName: string, workspaceName: string, options?: Models.ComponentContainersListOptionalParams): Promise<Models.ComponentContainersListResponse>;
  /**
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param callback The callback
   */
  list(resourceGroupName: string, workspaceName: string, callback: msRest.ServiceCallback<Models.ComponentContainerResourceArmPaginatedResult>): void;
  /**
   * @param resourceGroupName The name of the resource group. The name is case insensitive.
   * @param workspaceName Name of Azure Machine Learning workspace.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(resourceGroupName: string, workspaceName: string, options: Models.ComponentContainersListOptionalParams, callback: msRest.ServiceCallback<Models.ComponentContainerResourceArmPaginatedResult>): void;
  list(resourceGroupName: string, workspaceName: string, options?: Models.ComponentContainersListOptionalParams | msRest.ServiceCallback<Models.ComponentContainerResourceArmPaginatedResult>, callback?: msRest.ServiceCallback<Models.ComponentContainerResourceArmPaginatedResult>): Promise<Models.ComponentContainersListResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        workspaceName,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.ComponentContainersListResponse>;
  }

  /**
   * @summary List containers.
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.ComponentContainersListNextResponse>
   */
  listNext(nextPageLink: string, options?: Models.ComponentContainersListNextOptionalParams): Promise<Models.ComponentContainersListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.ComponentContainerResourceArmPaginatedResult>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: Models.ComponentContainersListNextOptionalParams, callback: msRest.ServiceCallback<Models.ComponentContainerResourceArmPaginatedResult>): void;
  listNext(nextPageLink: string, options?: Models.ComponentContainersListNextOptionalParams | msRest.ServiceCallback<Models.ComponentContainerResourceArmPaginatedResult>, callback?: msRest.ServiceCallback<Models.ComponentContainerResourceArmPaginatedResult>): Promise<Models.ComponentContainersListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.ComponentContainersListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const createOrUpdateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/components/{name}",
  urlParameters: [
    Parameters.name0,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "body",
    mapper: {
      ...Mappers.ComponentContainerResource,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.ComponentContainerResource
    },
    201: {
      bodyMapper: Mappers.ComponentContainerResource
    },
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};

const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/components/{name}",
  urlParameters: [
    Parameters.name1,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ComponentContainerResource
    },
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/components/{name}",
  urlParameters: [
    Parameters.name1,
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {},
    204: {},
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};

const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.MachineLearningServices/workspaces/{workspaceName}/components",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.workspaceName
  ],
  queryParameters: [
    Parameters.apiVersion,
    Parameters.skip
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ComponentContainerResourceArmPaginatedResult
    },
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  queryParameters: [
    Parameters.apiVersion,
    Parameters.skip
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ComponentContainerResourceArmPaginatedResult
    },
    default: {
      bodyMapper: Mappers.MachineLearningServiceError
    }
  },
  serializer
};
