/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export {
  BaseResource,
  ConfigurationIdentity,
  ErrorDefinition,
  ErrorResponse,
  ExtensionInstance,
  ExtensionInstancesList,
  ExtensionInstanceUpdate,
  ExtensionStatus,
  ProxyResource,
  Resource,
  Scope,
  ScopeCluster,
  ScopeNamespace,
  SystemData
} from "../models/mappers";
