/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export {
  AzureEntityResource,
  BaseResource,
  ConnectionDetail,
  ErrorAdditionalInfo,
  ErrorDetail,
  ErrorResponseCommon,
  ErrorResponseV2,
  ErrorResponseV2Error,
  HybridComputePrivateLinkScope,
  HybridComputePrivateLinkScopeListResult,
  Identity,
  LocationData,
  Machine,
  MachineExtension,
  MachineExtensionInstanceView,
  MachineExtensionInstanceViewStatus,
  MachineExtensionPropertiesInstanceView,
  MachineIdentity,
  MachinePropertiesOsProfile,
  OSProfile,
  PrivateEndpointConnection,
  PrivateEndpointProperty,
  PrivateLinkResource,
  PrivateLinkScopesResource,
  PrivateLinkScopeValidationDetails,
  PrivateLinkServiceConnectionStateProperty,
  ProxyResource,
  Resource,
  TagsResource,
  TrackedResource
} from "../models/mappers";
