/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/activeConfigurationsMappers";
import * as Parameters from "../models/parameters";
import { NetworkManagementClientContext } from "../networkManagementClientContext";

/** Class representing a ActiveConfigurations. */
export class ActiveConfigurations {
  private readonly client: NetworkManagementClientContext;

  /**
   * Create a ActiveConfigurations.
   * @param {NetworkManagementClientContext} client Reference to the service client.
   */
  constructor(client: NetworkManagementClientContext) {
    this.client = client;
  }

  /**
   * Lists active configurations in a network manager.
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param [options] The optional parameters
   * @returns Promise<Models.ActiveConfigurationsListResponse>
   */
  list(resourceGroupName: string, networkManagerName: string, options?: Models.ActiveConfigurationsListOptionalParams): Promise<Models.ActiveConfigurationsListResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param callback The callback
   */
  list(resourceGroupName: string, networkManagerName: string, callback: msRest.ServiceCallback<Models.ActiveConfigurationListResult>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(resourceGroupName: string, networkManagerName: string, options: Models.ActiveConfigurationsListOptionalParams, callback: msRest.ServiceCallback<Models.ActiveConfigurationListResult>): void;
  list(resourceGroupName: string, networkManagerName: string, options?: Models.ActiveConfigurationsListOptionalParams | msRest.ServiceCallback<Models.ActiveConfigurationListResult>, callback?: msRest.ServiceCallback<Models.ActiveConfigurationListResult>): Promise<Models.ActiveConfigurationsListResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        networkManagerName,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.ActiveConfigurationsListResponse>;
  }

  /**
   * Lists active configurations in a network manager.
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.ActiveConfigurationsListNextResponse>
   */
  listNext(nextPageLink: string, options?: Models.ActiveConfigurationsListNextOptionalParams): Promise<Models.ActiveConfigurationsListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.ActiveConfigurationListResult>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: Models.ActiveConfigurationsListNextOptionalParams, callback: msRest.ServiceCallback<Models.ActiveConfigurationListResult>): void;
  listNext(nextPageLink: string, options?: Models.ActiveConfigurationsListNextOptionalParams | msRest.ServiceCallback<Models.ActiveConfigurationListResult>, callback?: msRest.ServiceCallback<Models.ActiveConfigurationListResult>): Promise<Models.ActiveConfigurationsListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.ActiveConfigurationsListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkManagers/{networkManagerName}/activeConfigurations",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.networkManagerName
  ],
  queryParameters: [
    Parameters.apiVersion2,
    Parameters.top,
    Parameters.skipToken,
    Parameters.region
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ActiveConfigurationListResult
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  queryParameters: [
    Parameters.apiVersion2,
    Parameters.top,
    Parameters.skipToken,
    Parameters.region
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.ActiveConfigurationListResult
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
