/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/userRulesMappers";
import * as Parameters from "../models/parameters";
import { NetworkManagementClientContext } from "../networkManagementClientContext";

/** Class representing a UserRules. */
export class UserRules {
  private readonly client: NetworkManagementClientContext;

  /**
   * Create a UserRules.
   * @param {NetworkManagementClientContext} client Reference to the service client.
   */
  constructor(client: NetworkManagementClientContext) {
    this.client = client;
  }

  /**
   * Lists all user rules in a security configuration.
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param [options] The optional parameters
   * @returns Promise<Models.UserRulesListResponse>
   */
  list(resourceGroupName: string, networkManagerName: string, configurationName: string, options?: Models.UserRulesListOptionalParams): Promise<Models.UserRulesListResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param callback The callback
   */
  list(resourceGroupName: string, networkManagerName: string, configurationName: string, callback: msRest.ServiceCallback<Models.UserRuleListResult>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param options The optional parameters
   * @param callback The callback
   */
  list(resourceGroupName: string, networkManagerName: string, configurationName: string, options: Models.UserRulesListOptionalParams, callback: msRest.ServiceCallback<Models.UserRuleListResult>): void;
  list(resourceGroupName: string, networkManagerName: string, configurationName: string, options?: Models.UserRulesListOptionalParams | msRest.ServiceCallback<Models.UserRuleListResult>, callback?: msRest.ServiceCallback<Models.UserRuleListResult>): Promise<Models.UserRulesListResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        networkManagerName,
        configurationName,
        options
      },
      listOperationSpec,
      callback) as Promise<Models.UserRulesListResponse>;
  }

  /**
   * Gets a user rule.
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param [options] The optional parameters
   * @returns Promise<Models.UserRulesGetResponse>
   */
  get(resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options?: msRest.RequestOptionsBase): Promise<Models.UserRulesGetResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param callback The callback
   */
  get(resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, callback: msRest.ServiceCallback<Models.UserRule>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param options The optional parameters
   * @param callback The callback
   */
  get(resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.UserRule>): void;
  get(resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.UserRule>, callback?: msRest.ServiceCallback<Models.UserRule>): Promise<Models.UserRulesGetResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        networkManagerName,
        configurationName,
        ruleName,
        options
      },
      getOperationSpec,
      callback) as Promise<Models.UserRulesGetResponse>;
  }

  /**
   * Creates or updates a user rule.
   * @param userRule The user rule to create or update
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param [options] The optional parameters
   * @returns Promise<Models.UserRulesCreateOrUpdateResponse>
   */
  createOrUpdate(userRule: Models.UserRule, resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options?: msRest.RequestOptionsBase): Promise<Models.UserRulesCreateOrUpdateResponse>;
  /**
   * @param userRule The user rule to create or update
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param callback The callback
   */
  createOrUpdate(userRule: Models.UserRule, resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, callback: msRest.ServiceCallback<Models.UserRule>): void;
  /**
   * @param userRule The user rule to create or update
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param options The optional parameters
   * @param callback The callback
   */
  createOrUpdate(userRule: Models.UserRule, resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.UserRule>): void;
  createOrUpdate(userRule: Models.UserRule, resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.UserRule>, callback?: msRest.ServiceCallback<Models.UserRule>): Promise<Models.UserRulesCreateOrUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        userRule,
        resourceGroupName,
        networkManagerName,
        configurationName,
        ruleName,
        options
      },
      createOrUpdateOperationSpec,
      callback) as Promise<Models.UserRulesCreateOrUpdateResponse>;
  }

  /**
   * Deletes a user rule.
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteMethod(resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param callback The callback
   */
  deleteMethod(resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param resourceGroupName The name of the resource group.
   * @param networkManagerName The name of the network manager.
   * @param configurationName The name of the network manager security Configuration.
   * @param ruleName The name of the rule.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteMethod(resourceGroupName: string, networkManagerName: string, configurationName: string, ruleName: string, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        resourceGroupName,
        networkManagerName,
        configurationName,
        ruleName,
        options
      },
      deleteMethodOperationSpec,
      callback);
  }

  /**
   * Lists all user rules in a security configuration.
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param [options] The optional parameters
   * @returns Promise<Models.UserRulesListNextResponse>
   */
  listNext(nextPageLink: string, options?: Models.UserRulesListNextOptionalParams): Promise<Models.UserRulesListNextResponse>;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param callback The callback
   */
  listNext(nextPageLink: string, callback: msRest.ServiceCallback<Models.UserRuleListResult>): void;
  /**
   * @param nextPageLink The NextLink from the previous successful call to List operation.
   * @param options The optional parameters
   * @param callback The callback
   */
  listNext(nextPageLink: string, options: Models.UserRulesListNextOptionalParams, callback: msRest.ServiceCallback<Models.UserRuleListResult>): void;
  listNext(nextPageLink: string, options?: Models.UserRulesListNextOptionalParams | msRest.ServiceCallback<Models.UserRuleListResult>, callback?: msRest.ServiceCallback<Models.UserRuleListResult>): Promise<Models.UserRulesListNextResponse> {
    return this.client.sendOperationRequest(
      {
        nextPageLink,
        options
      },
      listNextOperationSpec,
      callback) as Promise<Models.UserRulesListNextResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkManagers/{networkManagerName}/securityConfigurations/{configurationName}/userRules",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.networkManagerName,
    Parameters.configurationName
  ],
  queryParameters: [
    Parameters.apiVersion2,
    Parameters.top,
    Parameters.skipToken
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.UserRuleListResult
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkManagers/{networkManagerName}/securityConfigurations/{configurationName}/userRules/{ruleName}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.networkManagerName,
    Parameters.configurationName,
    Parameters.ruleName
  ],
  queryParameters: [
    Parameters.apiVersion2
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.UserRule
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const createOrUpdateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkManagers/{networkManagerName}/securityConfigurations/{configurationName}/userRules/{ruleName}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.networkManagerName,
    Parameters.configurationName,
    Parameters.ruleName
  ],
  queryParameters: [
    Parameters.apiVersion2
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  requestBody: {
    parameterPath: "userRule",
    mapper: {
      ...Mappers.UserRule,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.UserRule
    },
    201: {
      bodyMapper: Mappers.UserRule
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network/networkManagers/{networkManagerName}/securityConfigurations/{configurationName}/userRules/{ruleName}",
  urlParameters: [
    Parameters.subscriptionId,
    Parameters.resourceGroupName,
    Parameters.networkManagerName,
    Parameters.configurationName,
    Parameters.ruleName
  ],
  queryParameters: [
    Parameters.apiVersion2
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {},
    204: {},
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};

const listNextOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  baseUrl: "https://management.azure.com",
  path: "{nextLink}",
  urlParameters: [
    Parameters.nextPageLink
  ],
  queryParameters: [
    Parameters.apiVersion2,
    Parameters.top,
    Parameters.skipToken
  ],
  headerParameters: [
    Parameters.acceptLanguage
  ],
  responses: {
    200: {
      bodyMapper: Mappers.UserRuleListResult
    },
    default: {
      bodyMapper: Mappers.CloudError
    }
  },
  serializer
};
