/*
 * Copyright (c) Microsoft Corporation.
 * Licensed under the MIT License.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is regenerated.
 */

export {
  BaseResource,
  CheckInstanceNameAvailabilityParameters,
  CheckInstanceNameAvailabilityResult,
  DFPInstance,
  DFPInstanceAdministrators,
  DFPInstances,
  DFPInstanceUpdateParameters,
  ErrorResponse,
  ErrorResponseError,
  Resource,
  SystemData
} from "../models/mappers";
